// <auto-generated />
using System;
using EcommerceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcommerceAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcommerceAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 4, 21, 5, 48, 159, DateTimeKind.Utc).AddTicks(8321),
                            Email = "ahmed@example.com",
                            Name = "Ahmed Hassan",
                            Phone = "+966501234567"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 4, 21, 5, 48, 159, DateTimeKind.Utc).AddTicks(8326),
                            Email = "fatima@example.com",
                            Name = "Fatima Al-Rashid",
                            Phone = "+966509876543"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 4, 21, 5, 48, 159, DateTimeKind.Utc).AddTicks(8328),
                            Email = "mohammed@example.com",
                            Name = "Mohammed Ali",
                            Phone = "+966551234567"
                        });
                });

            modelBuilder.Entity("EcommerceAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EcommerceAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EcommerceAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 4, 21, 5, 48, 159, DateTimeKind.Utc).AddTicks(8076),
                            Description = "High-performance laptop",
                            Name = "Laptop",
                            Price = 999.99m,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2026, 5, 4, 21, 5, 48, 159, DateTimeKind.Utc).AddTicks(8079)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 4, 21, 5, 48, 159, DateTimeKind.Utc).AddTicks(8086),
                            Description = "Wireless mouse",
                            Name = "Mouse",
                            Price = 29.99m,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2026, 5, 4, 21, 5, 48, 159, DateTimeKind.Utc).AddTicks(8086)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 4, 21, 5, 48, 159, DateTimeKind.Utc).AddTicks(8089),
                            Description = "Mechanical keyboard",
                            Name = "Keyboard",
                            Price = 79.99m,
                            StockQuantity = 30,
                            UpdatedAt = new DateTime(2026, 5, 4, 21, 5, 48, 159, DateTimeKind.Utc).AddTicks(8089)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 4, 21, 5, 48, 159, DateTimeKind.Utc).AddTicks(8091),
                            Description = "27-inch 4K monitor",
                            Name = "Monitor",
                            Price = 299.99m,
                            StockQuantity = 15,
                            UpdatedAt = new DateTime(2026, 5, 4, 21, 5, 48, 159, DateTimeKind.Utc).AddTicks(8091)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 4, 21, 5, 48, 159, DateTimeKind.Utc).AddTicks(8093),
                            Description = "High-speed USB-C cable",
                            Name = "USB-C Cable",
                            Price = 14.99m,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2026, 5, 4, 21, 5, 48, 159, DateTimeKind.Utc).AddTicks(8093)
                        });
                });

            modelBuilder.Entity("EcommerceAPI.Models.Order", b =>
                {
                    b.HasOne("EcommerceAPI.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EcommerceAPI.Models.OrderItem", b =>
                {
                    b.HasOne("EcommerceAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceAPI.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EcommerceAPI.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EcommerceAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EcommerceAPI.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
